### PR TITLE
Array of native values must be converted with AsSlice and not AsMapSlice

### PR DESCRIPTION
**Pull request by osharko**
Hi,
I found that the array of number or array of string was not converted.
The behavior was that array was initialized with the right length, but no value was inserted into it due the fact that the AsMapSlice was looking for an Object.
The correct way is to call  AsSlice instead of AsMapSlice.

### CODE REVIEW

**Comment by tgulacsi** [comment]
Can you add some test?

**Comment by osharko** [comment]
> 
As the previous times I have no way to test, but i created the test, it should work.
The concept is simple: A procedure return an object who hold an array of varchar, and then just make an AsMap.

**Comment by osharko** [comment]
Will this commit be released asap?

**Comment by tgulacsi** [comment]
Test/use it for a while, maybe you find more edge cases...

BTW I've fixed the test and moved it to `z_plsql_types_test.go`.

**Comment by osharko** [comment]
> Test/use it for a while, maybe you find more edge cases...
> 
> BTW I've fixed the test and moved it to `z_plsql_types_test.go`.

Ok, how do i add it to the go mod?

**Comment by osharko** [comment]
> Will this commit be released asap?
Oh right, ty
go get github.com/godror/godror@main

**Pull request merged**
