### PR TITLE
add u?int8 and u?int16 back

### PR DESCRIPTION
**Pull request by stevefan1999-personal**

### CODE REVIEW

**Comment by tgulacsi** [comment]
Why do you need int16? What for?

**Comment by stevefan1999-personal** [comment]
@tgulacsi for a orm dialect driver im using

**Comment by stevefan1999-personal** [comment]
if you are interested, [stevefan1999-personal/gorm-driver-oracle](https://github.com/stevefan1999-personal/gorm-driver-oracle) is the repo

**Comment by tgulacsi** [comment]
sql.NullInt32 is the only useful addition.

Shorter ints won't consume less resource on Oracle side, but increases the complexity, for no big achievements.

**Comment by stevefan1999-personal** [comment]
But I couldn’t create my Gorm entity if I use uint8/uint16...this is weird since other drivers supports uint8/uint16 as well, so it’s about the matter of completeness

**Comment by tgulacsi** [comment]
Please add tests for all the new types!

**Pull request merged**
